In [1]:
from scipy.optimize import differential_evolution

In [2]:
import numpy as np

In [3]:
def ackley(x):
    arg1 = -0.2 * np.sqrt(0.5 * (x[0] ** 2 + x[1] ** 2))
    arg2 = 0.5 * (np.cos(2. * np.pi * x[0]) + np.cos(2. * np.pi * x[1]))
    return -20. * np.exp(arg1) - np.exp(arg2) + 20. + np.e

In [4]:
bounds = [(-5, 5), (-5, 5)]

In [5]:
result = differential_evolution(ackley, bounds)

In [6]:
result.x

array([0., 0.])

In [7]:
result.fun

4.440892098500626e-16

In [8]:
def beale(x):
    arg1 = (1.5 - x[0] + x[0]*x[1])**2
    arg2 = (2.25 - x[0] + x[0]*x[1]**2)**2
    arg3 = (2.65 - x[0] + x[0]*x[1]**3)**2
    return arg1 + arg2 + arg3

In [9]:
bounds = [(-4.5, 4.5), (-4.5, 4.5)]

In [10]:
result = differential_evolution(beale, bounds)

In [12]:
result.x

array([3.05059444, 0.50986296])

In [13]:
def himmelblau(x):
    arg1 = (x[0]**2 + x[1] -11)**2
    arg2 = (x[0] + x[1]**2 -7)**2
    return arg1 + arg2

In [22]:
bounds = [(-5, 5), (-5, 5)]
result = differential_evolution(himmelblau, bounds)

In [23]:
result.x

array([3., 2.])